# basic info
user_name: "Bai Shuanghao"
repo_name: "cv-arxiv-daily"

show_badge: false
max_results: 60

publish_readme: true
publish_gitpage: true
publish_wechat: false

# file path 
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords
keywords:
  "Robot & Agent":
    filters: ["Embodied Agent", "Robot Learning", "Robot Policy", "Robot Policies", "Human-Robot", "Cross-Embodiment"]
  "Robotic Manipulation":
    filters: ["Manipulation", "Robot Manipulation", "Robotic Manipulation", "Grasp", "Robot Grasp", "World Model"]
  "Vision Language Action Model":
    filters: ["Vision-Language-Action Model", "Vision Language Action Model"]
  "Imitation Learning":
    filters: ["Imitation Learning", "Behavior Cloning", "Behavioral Cloning"]
  "Robotic Navigation":
    filters: ["Navigation", "Robot Navigation", "Vision-and-Language Navigation"]
